name: createstructure
version: '08.03'
summary: With this program, you can easily create a repository on GitHub.
description: |
 With this program, you can easily create a repository on GitHub with a basic template, personalized for your use.
 To see more visit: https://github.com/createstructure/createstructure/
  
grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64, arm64, armhf, i386, ppc64el, s390x]

parts:
 createstructure:
  plugin: cmake
  source: snap-bin

apps:
 createstructure:
  command: createstructure
