name: createstructure
version: '7.9'
summary: With this program, you can easily create a repository on GitHub.
description: |
 With this program, you can easily create a repository on GitHub with a basic template, personalized for your use.
 To see more visit: https://github.com/createstructure/createstructure/
  
grade: stable
confinement: strict

parts:
 createstructure:
  plugin: cmake
  source: snap-bin

apps:
 createstructure:
  command: createstructure
